<h2>About this Project</h2>
<p>In this project, you will implement a regression tree that predicts the severity of a patient's heart disease based on a set of attributes. The training data is in <code>heart_disease_train.csv</code> and the test data is in <code>heart_disease_test.csv</code>. Before you begin, take a look at the two csv files and  <code>attribute.txt</code>, which contains a description of each attribute in the csv files. You can download the files for review using the links below:</p>

* [heart_disease_train.csv](files/heart_disease_train.csv)</li>
* [heart_disease_test.csv](files/heart_disease_test.csv)
* [attribute.txt](files/attribute.txt)


<h3>Evaluation</h3>

<p><strong>This project must be successfully completed and submitted in order to receive credit for this course. Your score on this project will be included in your final grade calculation.</strong><p>
    
<p>You are expected to write code where you see <em># YOUR CODE HERE</em> within the cells of this notebook. Not all cells will be graded; code input cells followed by cells marked with <em>#Autograder test cell</em> will be graded. Upon submitting your work, the code you write at these designated positions will be assessed using an "autograder" that will run all test cells to assess your code. You will receive feedback from the autograder that will identify any errors in your code. Use this feedback to improve your code if you need to resubmit. Be sure not to change the names of any provided functions, classes, or variables within the existing code cells, as this will interfere with the autograder. Also, remember to execute all code cells sequentially, not just those you’ve edited, to ensure your code runs properly.</p>
    
<p>You can resubmit your work as many times as necessary before the submission deadline. If you experience difficulty or have questions about this exercise, use the Q&A discussion board to engage with your peers or seek assistance from the instructor.<p>

<p>Before starting your work, please review <a href="https://s3.amazonaws.com/ecornell/global/eCornellPlagiarismPolicy.pdf">eCornell's policy regarding plagiarism</a> (the presentation of someone else's work as your own without source credit).</p>

<h3>Submit Code for Autograder Feedback</h3>

<p>Once you have completed your work on this notebook, you will submit your code for autograder review. Follow these steps:</p>

<ol>
  <li><strong>Save your notebook.</strong></li>
  <li><strong>Mark as Completed —</strong> In the blue menu bar along the top of this code exercise window, you’ll see a menu item called <strong>Education</strong>. In the <strong>Education</strong> menu, click <strong>Mark as Completed</strong> to submit your code for autograder/instructor review. This process will take a moment and a progress bar will show you the status of your submission.</li>
	<li><strong>Review your results —</strong> Once your work is marked as complete, the results of the autograder will automatically be presented in a new tab within the code exercise window. You can click on the assessment name in this feedback window to see more details regarding specific feedback/errors in your code submission.</li>
  <li><strong>Repeat, if necessary —</strong> The Jupyter notebook will always remain accessible in the first tabbed window of the exercise. To reattempt the work, you will first need to click <strong>Mark as Uncompleted</strong> in the <strong>Education</strong> menu and then proceed to make edits to the notebook. Once you are ready to resubmit, follow steps one through three. You can repeat this procedure as many times as necessary.</li>
</ol>
<p>You can also download a copy of this notebook in multiple formats using the <strong>Download as</strong> option in the <strong>File</strong> menu above.</p>

## Getting Started

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys

%matplotlib inline

sys.path.append('/home/codio/workspace/.guides/hf')
from helper import *

print('You\'re running python %s' % sys.version.split(' ')[0])

You're running python 3.6.8


<h2>Implement a Regression Tree</h2>

<h3>Part One: Implement <code>load_data</code> [Graded]</h3>

Now, implement a function called <code>load_data</code>, which will load the given <code>.csv</code> file and return <code>X, y</code> where <code>X</code> are the patients' attributes and <code>y</code> is the severity of the patients' heart disease. <b>The function should handle two explicit cases. If label=True it should output the training data X and the corresponding label vector y; if label=False it should output only the training data 

In [62]:
file='heart_disease_train.csv'
data = np.loadtxt(open(file,'rb'),delimiter = ',',skiprows = 1)
y = data[:,13]
x = data[:,0:13]
print(data)
print(y)
print(x)

[[39.  1.  3. ...  0.  3.  0.]
 [47.  1.  3. ...  0.  3.  0.]
 [41.  1.  2. ...  0.  3.  0.]
 ...
 [63.  0.  4. ...  3.  7.  1.]
 [70.  1.  4. ...  0.  7.  1.]
 [64.  1.  4. ...  2.  6.  1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]
[[39.  1.  3. ...  1.  0.  3.]
 [47.  1.  3. ...  1.  0.  3.]
 [

In [78]:
def load_data(file='heart_disease_train.csv', label=True):
    '''
    Input:
        file: filename of the dataset
        label: a boolean to decide whether to return the labels or not
    Returns:
        X: patient attributes
        y: label (only if label=True)
    '''
    
    X = None
    y = None
    # YOUR CODE HERE
    data = np.loadtxt(open(file,'rb'),delimiter = ',',skiprows = 1)
    y = data[:,-1]
    X = data[:,0:13]
    if(label):
        return X,y
    else:
        return X
    raise NotImplementedError()
    


In [79]:
X, y = load_data()

In [80]:
# The following tests check that your load_data function reads in the correct number of rows, the correct number of unique values for y, and the same training data as the correct implementation

Xtrain, ytrain = load_data()
Xtrain_grader, ytrain_grader = load_data_grader()
Xtest = load_data(file='heart_disease_test.csv', label=False)
Xtest_grader = load_data_grader(file='heart_disease_test.csv', label=False)

def load_data_test1():
    return (len(Xtrain) == len(ytrain))

def load_data_test2():
    return (len(Xtrain) == len(Xtrain_grader))

def load_data_test3():
    y_unique = np.sort(np.unique(ytrain))
    y_grader_unique = np.sort(np.unique(ytrain_grader))
    
    if len(y_unique) != len(y_grader_unique):
        return False
    else:
        return np.linalg.norm(y_unique - y_grader_unique) < 1e-7
    
def load_data_test4():
    return(type(Xtrain)==np.ndarray and type(ytrain)==np.ndarray and type(Xtest)==np.ndarray)

def load_data_test5():
    Xtrain.sort()
    Xtrain_grader.sort()
    return np.linalg.norm(Xtrain-Xtrain_grader)<1e-07

def load_data_test6():
    ntr,dtr=Xtrain.shape
    nte,dte=Xtest.shape
    return dtr==dte

def load_data_test7():
    Xtest.sort()
    Xtest_grader.sort()
    return np.linalg.norm(Xtest-Xtest_grader)<1e-07

runtest(load_data_test1,'load_data_test1')
runtest(load_data_test2,'load_data_test2')
runtest(load_data_test3,'load_data_test3')
runtest(load_data_test4,'load_data_test4 (Testing for correct types)')
runtest(load_data_test5,'load_data_test5 (Testing training data for correctness)')
runtest(load_data_test6,'load_data_test6 (training and testing data dimensions should match)')
runtest(load_data_test7,'load_data_test7 (Testing test data for correctness)')



Running Test: load_data_test1 ... ✔ Passed!
Running Test: load_data_test2 ... ✔ Passed!
Running Test: load_data_test3 ... ✔ Passed!
Running Test: load_data_test4 (Testing for correct types) ... ✔ Passed!
Running Test: load_data_test5 (Testing training data for correctness) ... ✔ Passed!
Running Test: load_data_test6 (training and testing data dimensions should match) ... ✔ Passed!
Running Test: load_data_test7 (Testing test data for correctness) ... ✔ Passed!


In [81]:
# Autograder test cell - worth 1 point
# runs load_data test1

In [82]:
# Autograder test cell - worth 1 point
# runs load_data test2

In [83]:
# Autograder test cell - worth 1 point
# runs load_data test3

In [84]:
# Autograder test cell - worth 1 point
# runs load_data test4

In [85]:
# Autograder test cell - worth 1 point
# runs load_data test5

In [86]:
# Autograder test cell - worth 1 point
# runs load_data test6

In [87]:
# Autograder test cell - worth 1 point
# runs load_data test7

Now, you will use the regression tree from the previous assignment for this prediction problem. You can implement a regression tree using the function we've provided as demonstrated below:

In [88]:
# Create a regression with no restriction on its depth
# if you want to create a tree of depth k
# then call RegressionTree(depth=k)
tree = RegressionTree(depth=np.inf)

# To fit/train the regression tree
tree.fit(X, y)

# To use the trained regression tree to make predictions
pred = tree.predict(X)

<h3> Part Two: Find the Optimal Regression Tree [Graded]</h3>

In <code>test</code>, you will find the optimal regression tree for the dataset <code>heart_disease_train.csv</code> and return its prediction on <code>heart_disease_test.csv</code>. You will be evaluated based on <code>square_loss</code>. You will get a full score if the test loss on your classifier is less than <strong>0.17</strong>. You may use any functions that you implemented in the previous project.

In [93]:
def square_loss(pred, truth):
    return np.mean((pred - truth)**2)

In [97]:
def grid_search(xTr, yTr, xVal, yVal, depths):
    '''
    Input:
        xTr: nxd matrix
        yTr: n vector
        xVal: mxd matrix
        yVal: m vector
        depths: a list of len k
    Return:
        best_depth: the depth that yields that lowest loss on the validation set
        training losses: a list of len k. the i-th entry corresponds to the the training loss
                the tree of depths[i]
        validation_losses: a list of len k. the i-th entry corresponds to the the validation loss
                the tree of depths[i]
    '''

    
    # YOUR CODE HERE
    
    training_losses = []
    validation_losses = []
    best_depth = None
    
    lowest_loss = np.inf
    for i in depths:
        tree = RegressionTree(i)
        tree.fit(xTr, yTr)
        training_losses.append(square_loss(tree.predict(xTr), yTr))
        val_loss = square_loss(tree.predict(xVal), yVal)
        validation_losses.append(val_loss)
        if val_loss < lowest_loss:
            lowest_loss = val_loss
            best_depth = i
            
    return best_depth, training_losses, validation_losses



def generate_kFold(n, k):
    '''
    Input:
        n: number of training examples
        k: number of folds
    Returns:
        kfold_indices: a list of len k. Each entry takes the form
        (training indices, validation indices)
    '''
    assert k >= 2
    kfold_indices = [None]*k
    
    # YOUR CODE HERE
    folds = [None]*k
    for i in range(k):
        start_fold = int((i*n - (i*n)%k)/k)
        end_fold = int(((i+1)*n - ((i+1)*n)%k)/k)
        a = np.arange(0,start_fold)
        b = np.arange(end_fold,n)
        training_fold = list(np.append(a,b))
        validation_fold = list(np.arange(start_fold,end_fold))
        kfold_indices[i] = (training_fold,validation_fold)
    return kfold_indices


def cross_validation(xTr, yTr, depths, indices):
    '''
    Input:
        xTr: nxd matrix (training data)
        yTr: n vector (training data)
        depths: a list (of length l) depths to be tried out
        indices: indices from generate_kFold
    Returns:
        best_depth: the best parameter 
        training losses: a list of lenth l. the i-th entry corresponds to the the average training loss
                the tree of depths[i]
        validation_losses: a list of length l. the i-th entry corresponds to the the average validation loss
                the tree of depths[i] 
    '''
    l = len(depths)
    training_losses = [0]*l
    validation_losses = [0]*l
    best_depth = None
    
    # YOUR CODE HERE
    for i in indices:
        xTrain = xTr[i[0],:]
        yTrain = yTr[i[0]]
        xVal = xTr[i[1],:]
        yVal = yTr[i[1]]
        depth,training_loss,validation_loss = grid_search(xTrain,yTrain,xVal,yVal,depths)
        for n in range(l):
            training_losses[n] += training_loss[n]
            validation_losses[n] += validation_loss[n]
    best_depth = depths[np.argmin(validation_losses)]
    training_losses[:] = [x / len(indices) for x in training_losses]
    validation_losses[:] = [x / len(indices) for x in validation_losses]
    
    
    
    return best_depth, training_losses, validation_losses

In [135]:
depths = [1,2,3,4,5,6,7]
Xtrain, ytrain = load_data(file='heart_disease_train.csv', label=True)
Xtrain
ytrain=ytrain>0
Xtest = load_data(file='heart_disease_test.csv', label=False)
indices = generate_kFold(len(Xtrain), 5)
best_depth, training_losses, validation_losses = cross_validation(Xtrain, ytrain, depths, indices)
print(best_depth)
tree2 = RegressionTree(depth=best_depth+1)
tree2.fit(Xtrain,ytrain)
tree3 = RegressionTree(depth=best_depth-1)
tree3.fit(Xtrain,ytrain)
prediction2 = tree2.predict(Xtest)
prediction3 = tree3.predict(Xtest)
print((prediction2+prediction3))

2
[0.26196911 1.11217949 0.50142857 0.26196911 0.26196911 0.26196911
 0.26196911 1.11217949 1.58836996 1.58836996 0.26196911 0.26196911
 1.7443634  0.54142857 0.26196911 0.26196911 0.26196911 1.7443634
 0.50142857 1.11217949 1.11217949 0.50142857 0.26196911 1.7443634
 0.50142857 0.54142857 1.11217949 0.26196911 0.54142857 0.26196911
 0.26196911 1.11217949 1.58836996 1.7443634  1.7443634  1.58836996
 1.7443634  1.11217949 1.7443634  0.26196911 0.54142857 1.03392857
 1.11217949 0.26196911 1.7443634  1.7443634  1.11217949 1.58836996
 1.03392857 1.7443634  1.7443634  1.11217949 1.03392857 1.03392857
 1.7443634  1.7443634  1.11217949 1.7443634  1.7443634 ]


In [229]:
def test():
    '''
        prediction: the prediction of your classifier on the heart_disease_test.csv
    '''
    prediction = None
    Xtrain, ytrain = load_data(file='heart_disease_train.csv', label=True)
    ytrain=ytrain>0
    Xtest = load_data(file='heart_disease_test.csv', label=False)
    
    # YOUR CODE HERE
    depths = [1,2,3,4,5,6,7,8]
    indices = generate_kFold(len(Xtrain), 10)
    best_depth, training_losses, validation_losses = cross_validation(Xtrain, ytrain, depths, indices)
    tree1 = RegressionTree(depth=best_depth)
    tree1.fit(Xtrain,ytrain)
    tree2 = RegressionTree(depth=best_depth+1)
    tree2.fit(Xtrain,ytrain)
    tree3 = RegressionTree(depth=best_depth-1)
    tree3.fit(Xtrain,ytrain)
    prediction = (tree1.predict(Xtest) + tree2.predict(Xtest) + tree3.predict(Xtest))/3
    return prediction

In [230]:
# The following test wil check that your test function returns a loss less than 2 on a sample dataset
# ground truth:
gt = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

pred = test()
test_loss = square_loss(pred, gt)
print('Your test loss: {:0.4f}'.format(test_loss))

def test_loss_test():
    return (test_loss < 0.17)

runtest(test_loss_test, 'test_loss_test')

Your test loss: 0.1597
Running Test: test_loss_test ... ✔ Passed!


In [231]:
square_loss(np.mean(ytrain),gt)

0.248206469010062

In [232]:
ytrain=(ytrain>0)*1.0
ytrain

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [234]:
# Autograder test cell - worth 1 point
# runs test function test